network: {team_number: 9738, name: SynapseExample, ip: null, interface: null}
global:
  camera_configs:
    0:
      name: Integrated Camera
      id: Integrated Camera_47033
      transform:
      - [0.0, 0.0, 0.0]
      - [0.0, 0.0, 0.0]
      default_pipeline: 0
      stream_res: [320, 240]
      calibration: {}
pipelines:
  0:
    type: ApriltagPipeline
    settings: {fieldpose: true, iteration_count: 4.0, num_threads: 4.0, quad_decimate: 2.0,
      quad_sigma: 0.0, refine_edges: true, stick_to_ground: true, tag_family: tag36h11,
      tag_size: 0.1651, verbosity: 1}
    name: FieldPose
  1:
    type: ColorPipeline
    settings: {}
    name: Cheese
