name: SynapseLib Dev Auto CI

on:
  push:
    branches:
      - main
    paths:
      - "synapse_lib/**"

jobs:
  dev:
    uses: ./.github/workflows/synapse_lib_release.yml
    with:
      releaseVersion: dev
      forceDev: true
